name: Build PhantomLightEngine

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        build_type: [Debug, Release]
        
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup CMake
      uses: lukka/get-cmake@latest
      
    - name: Create Build Directory
      shell: cmd
      run: if not exist build mkdir build
      
    - name: Configure CMake
      shell: cmd
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      
    - name: Build
      shell: cmd
      run: cmake --build build --config ${{ matrix.build_type }}
      
    # 暂时注释掉测试步骤，因为可能还没有测试
    # - name: Run Tests
    #   working-directory: build
    #   run: ctest -C ${{ matrix.build_type }} --output-on-failure
      
    - name: List Build Output
      shell: cmd
      run: dir /s build
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PhantomLightEngine-${{ matrix.os }}-${{ matrix.build_type }}
        path: build
        if-no-files-found: warn
